### ISSUE TITLE
Missing header file; compilation error

### ISSUE THREAD

**Issue by rossobianero** [samsymons/Payments#1]
/Users/me/Library/Developer/Xcode/DerivedData/Payments-dharxubgtsmckcazjylrwkjitsep/Build/Intermediates/Payments.build/Debug-iphonesimulator/PaymentsCore.build/module.modulemap:9:12: error: header 'PaymentsCore-Swift.h' not found
    header "PaymentsCore-Swift.h"
           ^
/Users/me/Downloads/Payments-master/PaymentsIntentExtension/SendPaymentIntentHandler.swift:10:8: error: could not build Objective-C module 'PaymentsCore'
import PaymentsCore
       ^

**Comment by samsymons** [comment]
Thanks for checking this out — I suspect this project broke when new Xcode 8 betas came out. I'll take a look at getting it compiling again today!

**Comment by ycwjjjj** [comment]
I have encountered the same problem too. Please give us some insight or fix it if you could. Thanks a lot, Samsymons. 

Using Xcode Version 8.0 (8A218a)
